### PR TITLE
Interpret JSON Config values

### LINKED ISSUE #171: Automatically unmarshal complex configuration types
Non-primitive config fields are automatically `JSON.Stringify`-d when sent to the server:

https://github.com/pulumi/pulumi/blob/f500bef2fa732aab23c644dc07ed9b101a9cfaaf/pkg/codegen/nodejs/gen.go#L794-L797

```go
				// provider properties must be marshaled as JSON strings.
				if r.IsProvider && !isStringType(prop.Type) {
					arg = fmt.Sprintf("pulumi.output(%s).apply(JSON.stringify)", arg)
				}
```

However we aren't unmarshaling them on the receiving end. A type like this results in an error:

```
package foo

type Config struct {
   Foo []string `pulumi:"foo"`
}
```

>     error: ... provider returned an unexpected error from Configure: unknown mapper error: Field 'foo' on 'foo.Config' must be a '[]string'; got 'string' instead

The bridge seems to handle this here:

https://github.com/pulumi/pulumi-terraform-bridge/blob/0f7ccfdef31d3fddd4eb46c9770d460bbfbe81e3/pkg/tfbridge/config_encoding.go#L150C11-L174

```go
    var jsonString string
    var jsonStringDetected, jsonStringSecret bool


    if pv.IsString() {
        jsonString = pv.StringValue()
        jsonStringDetected = true
    }


    if opts.KeepSecrets && pv.IsSecret() && pv.SecretValue().Element.IsString() {
        jsonString = pv.SecretValue().Element.StringValue()
        jsonStringDetected = true
        jsonStringSecret = true
    }


    if jsonStringDetected {
        v, err := enc.convertStringToPropertyValue(jsonString, shimType)
        if err != nil {
            return nil, fmt.Errorf("error unmarshalling property %q: %w", key, err)
        }
        if jsonStringSecret {
            s := resource.MakeSecret(v)
            return &s, nil
        }
        return &v, nil
    }
```
I think this is essentially the issue:

https://github.com/pulumi/pulumi-go-provider/blob/2b02372596adf42516783cec8b6471be443195ef/provider.go#L710-L711

We unmarshal the provider's config the same way we unmarshal properties, but this JSON behavior is unique to config.

### PR DESCRIPTION
**Pull request by iwahbe**
This PR adds a middleware to handle decoding JSON encoded config values. The middleware is marked as deprecated, since we would like to remove this functionality as soon as https://github.com/pulumi/pulumi/pull/15032 closes.

Fixes #171

### CODE REVIEW

File: middleware/complexconfig/provider.go [hunk 1]
```diff
@@ -0,0 +1,178 @@
...
+	}
+
+	if putil.IsSecret(v) {
+		defer func() {
+			out = putil.MakeSecret(v)
+		}()
+		v = putil.MakePublic(v)
+	}
+
+	if !v.IsString() || spec.Type == "string" {
```
Comment (thomas11) [inline middleware/complexconfig/provider.go:103]: This seems like a bug at first glance - if it's _not_ a string or if it _is_ a string. But I think I get it now: if the value is not a string, we can't unmarshal it. If the value is string-typed in the spec, there's no point unmarshaling it since it's a primitive string.

**Review by thomas11 — APPROVED** [review]

File: middleware/complexconfig/provider.go (hunk 1 above)
Comment (iwahbe) [reply middleware/complexconfig/provider.go:103]: Yes! I see how that could be confusing though. I'll add ☝️ as a comment.

File: middleware/complexconfig/provider.go [hunk 2]
```diff
@@ -0,0 +1,181 @@
...
+				b, ok := v.(bool)
+				return ok && b
+			}
+
+			elem, hasElem := m["value"]
+
+			return resource.NewProperty(resource.Output{
+				Known:        hasElem,
+				Secret:       castBool("secret"),
+				Dependencies: nil,
```
Comment (t0yv0) [inline middleware/complexconfig/provider.go:171]: Always nil?

**Comment by t0yv0** [comment]
Does this need to cover old config in DiffConfig or CheckConfig suffices? Perhaps as a follow-up.

**Review by t0yv0 — APPROVED** [review]

File: middleware/complexconfig/provider.go (hunk 2 above)
Comment (iwahbe) [reply middleware/complexconfig/provider.go]: No. Good call. The rapid test property values didn't generate interesting dependency values. I addressed this and added valid support for dependency values in a subsequent push.

**Comment by iwahbe** [comment]
> Does this need to cover old config in DiffConfig or CheckConfig suffices? Perhaps as a follow-up.

I think it should be ok 🤞:

From `provider.proto`:

```proto
message DiffRequest {
    ...

    // the new input values of resource to diff, copied from CheckResponse.inputs.
    google.protobuf.Struct news = 4;

    ...
}
```

[src](https://github.com/pulumi/pulumi/blob/770eb1e5450c1e88d0d4ec921b643b9bd565dc74/proto/pulumi/provider.proto#L269-L270)

I'll double check that this applies for providers as well.

**Comment by iwahbe** [comment]
Check config is definitely called on new provider config before diff is called, so I think this should work by just overriding CheckConfig.
